### ISSUE TITLE
`WaitForNotBusy()` hangs forever if the chip does not respond

### ISSUE THREAD

**Issue by alex-kerner-ext-orion** [swharden/FTFlash#1]
Program freeze if: chip is connected incorrectly, chip is dead, bad contact of one of the wires.

This is due to the fact that the 0xFF value is read when polling the chip status.
This value is interpreted as "the chip is busy with some operation", and the program starts waiting for the chip in an infinite loop.
We need to fix the code, if 0xFF is read several times in a row, it is obvious that this is a chip fault and we need to exit with an error code (throw an exception).

Problem location:
https://github.com/swharden/FTFlash/blob/fed7a653a8320a8dd21cde03c760ea92f17a90a2/src/FTFlash/ProgForm.cs#L54

**Comment by swharden** [comment]
Thanks for reporting this @alex-kerner-ext-orion! I'll add a feature that cancels the attempt and launches a pop-up error message if the `WaitForNotBusy()` takes more than 1 second to complete

**Comment by swharden** [comment]
The next release will do something like this

![image](https://github.com/swharden/FTFlash/assets/4165489/c253061f-1781-4c48-b11d-c371a0139fa8)
