### ISSUE TITLE
Add a pinout diagram in the program

### ISSUE THREAD

**Issue by alex-kerner-ext-orion** [swharden/FTFlash#2]
Add button "Show pinout" that show this image:

![wiring](https://github.com/swharden/FTFlash/assets/95759482/f1440ccf-a54f-4718-bdec-6f8de1db5b69)

**Comment by swharden** [comment]
It's not fancy, but this may help!

![image](https://github.com/swharden/FTFlash/assets/4165489/1cc508a1-7abf-448e-b837-eaf0cc435d90)
