### ISSUE TITLE
Rouding down "pagesToWrite"

### ISSUE THREAD

**Issue by Donelook** [swharden/FTFlash#3]
Hello, 
i met issue in flashing w25q32 with FT232H when using your program. I have loaded program to my FLASH but it has not worked properly. I was searching so many possible mistake or reason. And i have got it - integer rouding down count of pages. Chatbot has written fix for it that you see below. Program with this fix work properly. Thank you for your program - is very helpful

```cs
private void btnWrite_Click(object sender, EventArgs e)
{
    OpenFileDialog diag = new() { Filter = "BIN files (*.bin)|*.bin|All files (*.*)|*.*" };
    if (diag.ShowDialog() != DialogResult.OK)
        return;
    byte[] fileBytes = File.ReadAllBytes(diag.FileName);

    SpiFlashManager? com = GetFlashMan();
    if (com is null)
        return;

    Progress($"Erasing chip...");
    com.Erase();

    int pagesToWrite = (int)Math.Ceiling((double)fileBytes.Length / 256);
    for (int i = 0; i < pagesToWrite; i++)
    {
        double percent = (double)i / pagesToWrite * 100;
        Progress($"Writing page {i} of {pagesToWrite} ({percent:0.00}%).", percent);
        byte[] pageBytes = new byte[256];
        int bytesRemaining = fileBytes.Length - i * 256;
        int bytesToCopy = Math.Min(256, bytesRemaining);
        Array.Copy(fileBytes, i * 256, pageBytes, 0, bytesToCopy);
        com.WritePage(i, pageBytes);
    }

    com.Disconnect();
    Progress($"Disconnected.");
}
```

![image](https://github.com/swharden/FTFlash/assets/14218650/6cf1c23a-a6e3-402e-9ce4-5f162b9f82cf)

**Comment by swharden** [comment]
Hi @Donelook, thanks for reporting this issue! It took me several weeks to get to this one 😅 

Do you still have your setup available so if I make the change you can test whether it works? I don't have a [w25q32](https://www.digikey.com/en/products/detail/winbond-electronics/W25Q32JVSSIQ/5803981) on hand myself...

**Comment by swharden** [comment]
Adding context, the error may be here:

https://github.com/swharden/FTFlash/blob/8a5b437e63fdf343774dd553c97907eaa41f1899/src/FTFlash/ProgForm.cs#L113

And the suggested solution is changing that one line to be:


```cs
int pagesToWrite = (int)Math.Ceiling((double)fileBytes.Length / 256);
```

**Comment by swharden** [comment]
https://github.com/swharden/FTFlash/releases/download/1.2/FTFlash.v1.2.zip
