### ISSUE TITLE
Write Error

### ISSUE THREAD

**Issue by faaytekin** [swharden/FTFlash#4]
Hello,
I am getting an error while writing to flash. I've attached the error message.
![image (4)](https://github.com/user-attachments/assets/09d7090d-b137-4e34-b67a-5dbfc8f572d7)

What could be the reason for this? Could you help to solve this issue?
Many thanks.

**Comment by swharden** [comment]
Interesting! Looks like some type of off by 1 error.

Can you double check exactly how large the data is you're trying to program? Could it be 1 byte shorter or longer than intended?

**Comment by swharden** [comment]
If you're able to zip the file and attach it as a comment, I could take a closer look

**Comment by faaytekin** [comment]
Thank you for your quick response.  
Nor Flash Memory
Manufacturer: Zetta
Model: ZD25WQ16
Size: 16Mbit
Bin file size: 62kb
The data size is very small compared to flash size.
I've attached the file.
[demo_V2.0.23_20240726.zip](https://github.com/user-attachments/files/17604097/demo_V2.0.23_20240726.zip)

Thanks a lot.

**Comment by faaytekin** [comment]
In addition, I've also tried using a few other bin files. I got the same result.

**Comment by swharden** [comment]
Thanks @faaytekin! I'm happy to take a closer look. When you get that error message, can you expand the "details" button and copy/paste the long error message here? That would really help. Thanks!

**Comment by faaytekin** [comment]
yes, of course. It is here.
![image (5)](https://github.com/user-attachments/assets/47044f45-81a0-4eab-a7a2-258499721587)

**Comment by faaytekin** [comment]
I attached the full error message.
[error_message.txt](https://github.com/user-attachments/files/17619898/error_message.txt)
I hope this helps to solve this issue.
Thank you.

**Comment by swharden** [comment]
Thanks! I'll take a closer look soon and let you know what I find.

```
System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
at FTFlash.ProgForm.btnWrite_Click(Object sender, EventArgs e) in C:\Users\scott\Documents\GitHub\FTFlash\src\FTFlash\ProgForm.cs:line 119
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by faaytekin** [comment]
Thank you so much. I am looking forward to hearing from you.

**Comment by swharden** [comment]
For more additional context, the exception message indicates the issue is on line 119

> `System.ArgumentException: Source array was not long enough.`

https://github.com/swharden/FTFlash/blob/d56e40de304183414f4f9238501aa1031fa3d3ff/src/FTFlash/ProgForm.cs#L104

https://github.com/swharden/FTFlash/blob/d56e40de304183414f4f9238501aa1031fa3d3ff/src/FTFlash/ProgForm.cs#L113-L121

... so I still suspect that the source file being programmed is shorter than expected.

@faaytekin can you double-check to confirm your source file is 2,097,152 bytes? I also am noticing that there is a difference between `Mb` (million bits) and `MB` (million bytes) so maybe there's an off-by-8 issue somewhere here

**Comment by swharden** [comment]
Looking closer, maybe the issue affects files whose length is not an even multiple of `256` (the page size for the flash memory)

A fix on the user end could be padding their source file to ensure this is satisfied.

A fix on our end (better) could be recognizing this case and padding the array with zeros at the end to avoid this exception.

**Comment by swharden** [comment]
Ha, I'm now realizing that a similar issue was described in #3, and that user provided some code that "fixed" it but it looks like they used ChatGPT to generate that code 😅😅😅 so this section will benefit from close scrutiny

**Comment by swharden** [comment]
Hi @faaytekin, I think I fixed this issue. Want to try the latest release and let me know if it did the trick? 
* https://github.com/swharden/FTFlash/releases/download/1.3/FTFlash1.3.zip
* https://github.com/swharden/FTFlash/releases/tag/1.3

**Comment by faaytekin** [comment]
Hello @swharden;
Thank you for your effort. I tried this new version and it works well.
Thanks a lot.

**Comment by swharden** [comment]
That's great news! Let me know if any other issues or questions come up along the way and we can take a look together. 

Thanks again, and happy programming!
